---
title: "mice"
output: html_document
---

```{r}
library(mice)
set.seed(100123)
vartype <- rep("numeric",550)
vartype[c(2,4,6,13,15,17,18,19,22,24,26,28,30,33,35,37,40,43,45,47,49)] <- "factor"
vartype[c(50,51,52,53,54,55,56,57,60,62,63,64,67,69,70,71,72,74,78)] <- "factor"
vartype[c(79,80,81,82,84,86,87,88,89,90,91,94,244,245,247,359,361,362)] <- "factor"
vartype[c(363,364,366,367,368,369,372,374,376,378,379,380,383,385)] <- "factor"
vartype[c(387,389,391,393,395,397,398,399,401,403,405,407,409,411)] <- "factor"
vartype[c(413,415,417,419,422,424,426,428,430,432,433,434,436,438)] <- "factor"
vartype[c(440,442,444,446,448,450,452,453,455,457,459,461,462,464)] <- "factor"
vartype[c(466,468,470,472,474,476,478,480,481,483,485,487,489,491)] <- "factor"
vartype[c(493,495,497,499,501,503,505,507,509,511,513,515,517,519)] <- "factor"
vartype[c(521,523,525,527,528,529,533,534,535,536,537,538,539,540)] <- "factor"
vartype[c(541,542,543,544,545,546,547,548)] <- "factor"
z <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/ce2021.txt",header=TRUE,colClasses=vartype)
```


```{r}

j <- which(names(z) == "FINLWT21")
z <- z[,-j] ## do not use weight to impute missing values
init = mice(z, maxit=0)
predM = init$predictorMatrix
num <- 2 ### number of imputed data sets desired
imputed <- mice(z, method=init$meth, predictorMatrix=predM, m=num)

```

```{r}
imputed.1 <- complete(imputed,1) # 1st imputed dataset
imputed.2 <- complete(imputed,2) # 2nd imputed dataset
```


```{r}
library(Amelia)
set.seed(1234)

exclude <- which(names(z) %in% c("FINLWT21","WHLFYR","DIRACC","TOTHVHRP",
"TOTHVHRC","ROTHRFLC","WELFREBX","OTHLNYR","STDNTYR","STOCKYR"))
z <- z[,-exclude] ## exclude weight and variables that do not vary
num.vars <- as.numeric(which(sapply(z,class) == "numeric"))
int.vars <- NULL
for(j in num.vars){
x <- z[,j]
x <- x[!is.na(x)]
if(all(x == floor(x))) int.vars <- c(int.vars,j) # largest integer right below the highest number please 
}
num <- 2 ### number of imputed data sets desired
### noms gives column numbers of nominal variables
noms <- as.numeric(which(sapply(z,class) == "factor"))
### ords gives column numbers of integer-valued ordinal

amelia.out <- amelia(z,m=num,noms=noms,ords=int.vars)

```


```{r}
imputed1 <- amelia.out$imputations$imp1 ## 1st imputed set
imputed2 <- amelia.out$imputations$imp2 ## 2nd imputed set
```












### 10  Marxch 

```{r}
vartype <- rep("numeric",550)
vartype[c(2,4,6,13,15,17,18,19,22,24,26,28,30,33,35,37)] <- "factor"
vartype[c(40,43,45,47,49,50,51,52,53,54,55,56,57,60,62)] <- "factor"
vartype[c(63,64,67,69,70,71,72,74,78,79,80,81,82,84,86)] <- "factor"
vartype[c(87,88,89,90,91,94,244,245,247,359,361,362,363)] <- "factor"
vartype[c(364,366,367,368,369,372,374,376,378,379,380)] <- "factor"
vartype[c(383,385,387,389,391,393,395,397,398,399,401)] <- "factor"
vartype[c(403,405,407,409,411,413,415,417,419,422,424)] <- "factor"
vartype[c(426,428,430,432,433,434,436,438,440,442,444)] <- "factor"
vartype[c(446,448,450,452,453,455,457,459,461,462,464)] <- "factor"
vartype[c(466,468,470,472,474,476,478,480,481,483,485)] <- "factor"
vartype[c(487,489,491,493,495,497,499,501,503,505,507)] <- "factor"
vartype[c(509,511,513,515,517,519,521,523,525,527,528)] <- "factor"
vartype[c(529,533,534,535,536,537,538,539,540,541,542)] <- "factor"
vartype[c(543,544,545,546,547,548)] <- "factor"
z <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/ce2021.txt",header=TRUE,colClasses=vartype)
```


```{r}
library(mice)
set.seed(1234)
exclude <- which(names(z) %in% c("FINLWT21"))
z <- z[,-exclude] 
init = mice(z, maxit=0)
predM = init$predictorMatrix
num <- 2 ### number of imputed data sets desired
imputed <- mice(z,method=init$meth,predictorMatrix=predM,m=num)
```
