---
title: "plot_imp_score"
output: html_document
---

```{r fig.height=15, fig.width=15}
leg.col <- c("red","orange","yellow","green","blue","gray")
leg.txt <- c(expression(phantom() >= "99% confidence"),
"95-99% confidence","90-95% confidence","80-90% confidence",
"50-80% confidence",expression(paste(phantom() < "50% confidence")))
par(las=1,mar=c(1,12,4,2),cex=1.1)
x <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/imp_scr.txt",header=TRUE)
score <- x$Score
vars <- x$Variable
group <- x$Group
barcol <- rep(leg.col[1],length(vars))
barcol[group == "B"] <- leg.col[2]
barcol[group == "C"] <- leg.col[3]
barcol[group == "D"] <- leg.col[4]
barcol[group == "E"] <- leg.col[5]
barcol[group == "F"] <- leg.col[6]
n <- 30 ### number of scores plotted
barplot(rev(score[1:n]),names.arg=rev(vars[1:n]),
col=rev(barcol[1:n]),horiz=TRUE,xlab="GUIDE importance scores")
legend("bottomright",legend=leg.txt,fill=leg.col)


```



99% CT means that theres only 1% chance that the variable is a fluke 







Least important 
```{r}
leg.col <- c("red","orange","yellow","green","blue","gray")
leg.txt <- c(expression(phantom() >= "99% confidence"),
"95-99% confidence","90-95% confidence","80-90% confidence",
"50-80% confidence",expression(paste(phantom() < "50% confidence")))
par(las=1,mar=c(1,12,4,2),cex=1.1)
x <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/imp_scr.txt",header=TRUE)
x <- x[nrow(x):1, ]
score <- x$Score
vars <- x$Variable
group <- x$Group
barcol <- rep(leg.col[1],length(vars))
barcol[group == "B"] <- leg.col[2]
barcol[group == "C"] <- leg.col[3]
barcol[group == "D"] <- leg.col[4]
barcol[group == "E"] <- leg.col[5]
barcol[group == "F"] <- leg.col[6]
n <- 30 ### number of scores plotted
barplot(rev(score[1:n]),names.arg=rev(vars[1:n]),
col=rev(barcol[1:n]),horiz=TRUE,xlab="GUIDE importance scores")
legend("bottomright",legend=leg.txt,fill=leg.col)

```


```{r}
x <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/ce2021.txt",header=TRUE)
length(x$STOCKX)
summary(x$STOCKX)
```



```{r}
leg.col <- c("red","orange","yellow","green","blue","gray")
leg.txt <- c(expression(phantom() >= "99% confidence"),
"95-99% confidence","90-95% confidence","80-90% confidence",
"50-80% confidence",expression(paste(phantom() < "50% confidence")))
par(las=1,mar=c(1,12,4,2),cex=1.1)
x <- read.table("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/imp_body_scr.txt",header=TRUE)
score <- x$Score
vars <- x$Variable
group <- x$Group
barcol <- rep(leg.col[1],length(vars))
barcol[group == "B"] <- leg.col[2]
barcol[group == "C"] <- leg.col[3]
barcol[group == "D"] <- leg.col[4]
barcol[group == "E"] <- leg.col[5]
barcol[group == "F"] <- leg.col[6]
n <- 24 ### number of scores plotted
barplot(rev(score[1:n]),names.arg=rev(vars[1:n]),
col=rev(barcol[1:n]),horiz=TRUE,xlab="GUIDE importance scores")
legend("bottomright",legend=leg.txt,fill=leg.col)

```




/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/survival_death_5yrs


```{r}
png("/Users/sorenbasnet/Desktop/importance_plot.png", width=2500, height=1200, res=150)

leg.col <- c("red","orange","yellow","green","blue","gray")
leg.txt <- c(expression(phantom() >= "99% confidence"),
"95-99% confidence","90-95% confidence","80-90% confidence",
"50-80% confidence",expression(paste(phantom() < "50% confidence")))
par(las=1,mar=c(1,12,4,2),cex=1.1)
x <- read.table("/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/survival_death_5yrs/imp_src.txt",header=TRUE)
score <- x$Score
vars <- x$Variable
group <- x$Group
barcol <- rep(leg.col[1],length(vars))
barcol[group == "B"] <- leg.col[2]
barcol[group == "C"] <- leg.col[3]
barcol[group == "D"] <- leg.col[4]
barcol[group == "E"] <- leg.col[5]
barcol[group == "F"] <- leg.col[6]
n <- 15 ### number of scores plotted
barplot(rev(score[1:n]),names.arg=rev(vars[1:n]),
col=rev(barcol[1:n]),horiz=TRUE,xlab="GUIDE importance scores")
legend("bottomright",legend=leg.txt,fill=leg.col)
dev.off()
```
```