---
title: "rpart_ct"
output: html_document
---

```{r}

library(rpart)
library(rpart.plot)

```

```{r}
z <- read.table(file="/Users/sorenbasnet/Desktop/STAT_443_SP_2026/Data_files_export/bodydata.txt",header=TRUE)
z$Gender <- as.factor(z$Gender)
par(cex=1.5)
rp <- rpart(Gender ~ .,data=z,method="class")
rpart.plot(rp,type=2,fallen.leaves=FALSE)


```

```{r}
rp
```
root node has 507 observation and 247 F. 51% F and 48% Male 
then it goes to node 2: 
  Forearmgirth < 25.65 ( game like guide ). but there is <= sign in guide tho 
  248 obv and 18 F 
    4) Biacronialdiam and so on ... 
    * tells you that it is terminal node 

```{r}
rp.pred <- predict(rp,newdata=z,type="class")
table(rp.pred,z$Gender)
```


```{r}

source("/Users/sorenbasnet/Desktop/STAT_443_SP_2026/guide_dataset/datafiles/")
```



# ce data 

```{r}
z <- read.table(file="/Users/sorenbasnet/Desktop/STAT_443_SP_2026/Data_files_export/ce2021.txt",header=TRUE)
summary(as.factor(z$EARNCOMP))


rp <- rpart(INTRDVX ~ . - INTRDVX_, data=z, weights=FINLWT21,method="anova")
rpart.plot(rp)


```





