---
title: "simulation"
output: html_document
---

```{r}
library(rpart)
library(ranger)
library(randomForest)
library(partykit)
```

```{r}
z <- read.table("realdata.txt",header=TRUE)
z$y <- as.factor(z$y)
z$sex <- as.factor(z$sex)
y <- z$y
n <- nrow(z)
nsim <- 10
cf.err <- 0
cf.err2 <- 0
ct.err <- 0
ct.err2 <- 0
rp.err <- 0
rp.err2 <- 0
ran.err <- 0
ran.err2 <- 0
gcon.err <- 0
gcon.err2 <- 0
gforest.err <- 0
gforest.err2 <- 0
April 8, 2026 STAT 443: Classification and Regression Trees (Loh) 280
for(i in 1:nsim){
ran <- rbinom(n,1,0.5)
train <- ran == 1
test <- ran == 0
### ctree
ct <- ctree(y ~ .,data=z[train,])
ct.pred <- predict(ct,newdata=z[test,])
error <- mean(y[test] != ct.pred)
ct.err <- ct.err+error
ct.err2 <- ct.err2+error*error
### cforest
cf <- cforest(y ~ .,data=z[train,])
cf.pred <- predict(cf,newdata=z[test,])
error <- mean(y[test] != cf.pred)
cf.err <- cf.err+error
cf.err2 <- cf.err2+error*error
### rpart
rp <- rpart(y ~ .,data=z[train,], method="class")
rp.pred <- predict(rp,newdata=z[test,],type="class")
error <- mean(y[test] != rp.pred)
rp.err <- rp.err+error
rp.err2 <- rp.err2+error*error
### ranger
ran <- ranger(y ~ .,data=z[train,])
ran.pred <- predict(ran,data=z[test,])$predictions
error <- mean(y[test] != ran.pred)
ran.err <- ran.err+error
ran.err2 <- ran.err2+error*error
April 8, 2026 STAT 443: Classification and Regression Trees (Loh) 281
### guide constant tree
z0 <- z
z0$y[test] <- NA
write.table(z0,"simdata.txt",row.names=FALSE,col.names=TRUE)
## IMPORTANT: choose mac or windows
system("../guide < simcons.in > simcons.log") ## mac osx
system("..\\guide < simcons.in > simcons.log") ## windows
z1 <- read.table("simcons.fit",header=TRUE)
gcon.pred <- z1$predicted[test]
error <- mean(as.character(y[test]) != gcon.pred)
gcon.err <- gcon.err+error
gcon.err2 <- gcon.err2+error*error
### guide forest
## IMPORTANT: choose mac or windows
system("../guide < simgforest.in > simgforest.log") ## mac
system("..\\guide < simgforest.in > simgforest.log") ## windows
z1 <- read.table("simgforest.fit",header=TRUE)
gforest.pred <- z1$predicted[test]
error <- mean(as.character(y[test]) != gforest.pred)
gforest.err <- gforest.err+error
gforest.err2 <- gforest.err2+error*error
April 8, 2026 STAT 443: Classification and Regression Trees (Loh) 282
if(i == nsim | i==5*floor(i/5)){
print(paste("Number of iterations completed =",i),quote=FALSE)
ct.mean <- ct.err/i
ct.se <- sqrt((ct.err2-i*ct.mean^2)/(i*(i-1)))
print(paste("ctree error and SE =",ct.mean,ct.se),quote=FALSE)
gcon.mean <- gcon.err/i
gcon.se <- sqrt((gcon.err2-i*gcon.mean^2)/(i*(i-1)))
print(paste("Guide constant error and SE =",gcon.mean,gcon.se),quote=FALSE)
rp.mean <- rp.err/i
rp.se <- sqrt((rp.err2-i*rp.mean^2)/(i*(i-1)))
print(paste("rpart error and SE =",rp.mean,rp.se),quote=FALSE)
cf.mean <- cf.err/i
cf.se <- sqrt((cf.err2-i*cf.mean^2)/(i*(i-1)))
print(paste("cforest error and SE =",cf.mean,cf.se),quote=FALSE)
ran.mean <- ran.err/i
ran.se <- sqrt((ran.err2-i*ran.mean^2)/(i*(i-1)))
print(paste("ranger error and SE =",ran.mean,ran.se),quote=FALSE)
gforest.mean <- gforest.err/i
gforest.se <- sqrt((gforest.err2-i*gforest.mean^2)/(i*(i-1)))
print(paste("Guide forest error and SE =",gforest.mean,gforest.se),quote=FALSE)
}
}
```