---
title: "traditional_R_surv"
output: html_document
---

```{r}
library(survival)
library(survminer)
library(dplyr)
```


```{r}
dataset_path <- "/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/"
```

```{r}
data_mutations <- read.table(file.path(dataset_path,"data_patient_mutation_march_8.txt"),header=TRUE, sep=" ")

```

```{r}
table(data_mutations$OS_STATUS)
```

```{r}
data_mutations$OS_STATUS <- ifelse(data_mutations$OS_STATUS == "DECEASED", 1, 0)
```


```{r}
table(data_mutations$OS_STATUS)
```


Create survival object
```{r}
surv_object <- Surv(time = data_mutations$OS_MONTHS, event = data_mutations$OS_STATUS)
```

Survival by IGHV mutation 
```{r}
fit <- survfit(surv_object ~ data_mutations$IGHV_MUTATION_STATUS, data=data_mutations)
```


Plot: 
```{r}
ggsurvplot(
  fit,
  data = data_mutations,
  pval = TRUE,
  risk.table = TRUE,
  conf.int = TRUE)
```



Survival by gene mutation 
```{r}

fit_tp53 <- survfit(surv_object ~ data_mutations$TP53BP2 + data_mutations$TP53INP2 + data_mutations$TP53TG5, data=data_mutations)
```


```{r}
ggsurvplot(
  fit_tp53,
  data = data_mutations,
  pval = TRUE,
  risk.table = TRUE
)
```






