---
title: "03_GWAS"
output: html_document
---

```{r}
library(survival)
library(survminer)
library(dplyr)
```


```{r}
dataset_path <- "/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/"
```

```{r}
data_mutations <- read.table(file.path(dataset_path,"data_patient_mutation_march_8.txt"),header=TRUE, sep=" ")

```


```{r}
data_mutations$OS_STATUS <- ifelse(data_mutations$OS_STATUS == "DECEASED", 1, 0)
```


```{r}
str(data_mutations$OS_MONTHS)
str(data_mutations$OS_STATUS)

data_mutations$OS_MONTHS <- as.numeric(data_mutations$OS_MONTHS)
data_mutations$OS_STATUS <- as.numeric(data_mutations$OS_STATUS)
```

```{r}
table(data_mutations$OS_STATUS)
```

```{r}
surv_object <- Surv(time = data_mutations$OS_MONTHS, event = data_mutations$OS_STATUS)
```


This dont work 
```{r}
genes <- colnames(data)[42:ncol(data_mutations)]

results <- data.frame()

for(g in genes){
  
  model <- coxph(
    as.formula(paste("Surv(OS_MONTHS, OS_STATUS) ~", g)),
    data = data
  )
  
  s <- summary(model)
  
  results <- rbind(
    results,
    data.frame(
      gene = g,
      HR = s$coef[1,2],
      p = s$coef[1,5]
    )
  )
}

results <- results %>% arrange(p)
```
