---
title: "data_mutations"
output: html_document
---

Import required library
```{r}
library(dplyr)
library(gtsummary)
library(kableExtra)
library(tidyr)
library(janitor)
library(tidyverse)
```

```{r}
dataset_path <- "/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/raw/cll_broad_2022"
```

```{r}
data_mutations <- read.table(file.path(dataset_path,"data_mutations.txt"),header=TRUE, sep="\t")

tp53_subset <- data_mutations %>% filter(str_detect(data_mutations$Hugo_Symbol, "TP53"))
unique(tp53_subset$Hugo_Symbol)
length(tp53_subset$Hugo_Symbol)

tp53_subset <- data_mutations %>% filter(str_detect(data_mutations$Hugo_Symbol, "SF3B1"))
unique(tp53_subset$Hugo_Symbol)
length(tp53_subset$Hugo_Symbol)

tp53_subset <- data_mutations %>% filter(str_detect(data_mutations$Hugo_Symbol, "NOTCH1"))
unique(tp53_subset$Hugo_Symbol)
length(tp53_subset$Hugo_Symbol)

summary(as.factor(data_mutations$Hugo_Symbol))

```

```{r}
colnames(data_mutations)
```

Dataframe for a CLL driver importance score
```{r}
mutation_matrix <- data_mutations %>% select(Hugo_Symbol, Tumor_Sample_Barcode, Consequence)

mutation_matrix <- mutation_matrix %>%
  mutate(value = 1) %>%
  distinct(Tumor_Sample_Barcode, Hugo_Symbol, .keep_all = TRUE) %>%
  pivot_wider(
    names_from = Hugo_Symbol,
    values_from = value,
    values_fill = 0
  )

dim(mutation_matrix)
```

Change all commas to something else 
```{r}
mutation_matrix <- mutation_matrix %>% mutate(across(where(is.character), ~ gsub(",", "__", .)))
mutation_matrix <- mutation_matrix %>% mutate(across(where(is.character), ~ gsub(" ", "__", .)))
mutation_matrix <- mutation_matrix %>% mutate(across(where(is.character), ~ gsub("-", "_", .)))
mutation_matrix <- mutation_matrix %>% mutate(across(where(is.character), ~ gsub("/", "_", .)))

# This creates a small 5x6 slice of your matrix

unique(mutation_matrix$Consequence)


mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "splice_region_variant__synonymous_variant"] <- "srvsv"
mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "splice_acceptor_variant__coding_sequence_variant"] <- "savcsv"
mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "missense_variant__splice_region_variant"] <- "mvsrv"
mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "splice_acceptor_variant__non_coding_transcript_variant"] <- "savntv"

mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "splice_acceptor_variant__coding_sequence_variant__intron_variant"] <- "savcsviv"

mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "splice_region_variant__splice_polypyrimidine_tract_variant__intron_variant"] <- "srvsptviv"

mutation_matrix$Consequence[mutation_matrix$Consequence == 
  "intron_variant__non_coding_transcript_variant"] <- "ivnctv"


mutation_matrix[is.na(mutation_matrix)] <- NA
```


Save mutation matrix 
```{r}
write.table(mutation_matrix, "/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/mutation_matrix_march_7.txt", sep=" ", row.names = FALSE, quote = FALSE)

str(mutation_matrix[, 1:5])

```






