---
title: "dsc_file"
output: html_document
---

Dsc file for mutation matrix 
Intended to see the importance score of each score
```{r}
z <- read.table("/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/mutation_matrix.txt",header=TRUE)
nvars <- ncol(z)
write("mutation_matrix.txt",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/dsc_mutation_matrix.txt")
write("NA",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/dsc_mutation_matrix.txt",append=TRUE)
write("2",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/dsc_mutation_matrix.txt",append=TRUE)
roles <- rep("n",nvars)
write.table(cbind(1:nvars,names(z),roles),file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/processed/dsc_mutation_matrix.txt",
col.names=FALSE,row.names=FALSE,append=TRUE,quote=FALSE)
```



Dsc file for patient_mutation  
Intended to see the importance score of each score
```{r}
z <- read.table("/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/patient_mutation_march_7.txt",header=TRUE, sep=" ")
nvars <- ncol(z)
write("patient_mutation_march_7.txt",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/dsc_patient_mutation_march_7.txt")
write("NA",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/dsc_patient_mutation_march_7.txt",append=TRUE)
write("2",file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/dsc_patient_mutation_march_7.txt",append=TRUE)
roles <- rep("n",nvars)
write.table(cbind(1:nvars,names(z),roles),file="/Users/sorenbasnet/Documents/Github/STAT_443_FINAL_PROJECT/data/interim/dsc_patient_mutation_march_7.txt", col.names=FALSE,row.names=FALSE,append=TRUE,quote=FALSE)
```